// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = const FirebaseOptions(
    apiKey: 'AIzaSyC_dwEUxuaxBpGQcfltZg4HCFpg4BW9U3M',
    appId: '1:676771940075:web:3bd320142638dcbf2220ae',
    messagingSenderId: '676771940075',
    projectId: 'app-aluno-online',
    authDomain: 'app-aluno-online.firebaseapp.com',
    storageBucket: 'app-aluno-online.appspot.com',
  );

  static FirebaseOptions android = const FirebaseOptions(
    apiKey: 'AIzaSyDIUhvTU78tc2t-RZN8BSlLFfsVCoae5xE',
    appId: '1:676771940075:android:5902a167f4d127092220ae',
    messagingSenderId: '676771940075',
    projectId: 'app-aluno-online',
    storageBucket: 'app-aluno-online.appspot.com',
  );

  static FirebaseOptions ios = const FirebaseOptions(
    apiKey: 'AIzaSyCEQBpi5jR98Tc3I-Jvegz_c0_m8KPLqqI',
    appId: '1:676771940075:ios:1e9c8d272a89aac32220ae',
    messagingSenderId: '676771940075',
    projectId: 'app-aluno-online',
    storageBucket: 'app-aluno-online.appspot.com',
    iosClientId:
        '676771940075-a63ekvf3b0inmm5lsfnpepvp7sgqfvaf.apps.googleusercontent.com',
    iosBundleId: 'br.com.gmtta.appAlunoOnline',
  );
}
